ANGRY = ' assets/expressions/angry.mp4'
BLINK = ' assets/expressions/blink.mp4'
EXCITED = ' assets/expressions/excited.mp4'
LOVE = ' assets/expressions/love.mp4'
NEUTRAL = ' assets/expressions/neutral.mp4'
SAD = ' assets/expressions/sad.mp4'
SHOCK = ' assets/expressions/shock.mp4'
SLEEPY = ' assets/expressions/sleepy.mp4'
